default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: ecommerce_api_development
  username: postgres
  password: postgres
  host: 127.0.0.1
  port: 5433

test:
  <<: *default
  database: ecommerce_api_test
  username: postgres
  password: postgres
  host: 127.0.0.1
  port: 5433

production:
  <<: *default
  database: ecommerce_api_production
  username: ecommerce_api
  password: <%= ENV['ECOMMERCE_API_DATABASE_PASSWORD'] %>
